// <auto-generated />
using EfCoreMigrationandConfiguration.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCoreMigrationandConfiguration.Migrations
{
    [DbContext(typeof(OkulDbContex))]
    [Migration("20220903102043_AddRelation")]
    partial class AddRelation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EfCoreMigrationandConfiguration.Models.Not", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("Final")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("NotAdi")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("OgrNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("Vize")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("OgrNo");

                    b.ToTable("Not", (string)null);
                });

            modelBuilder.Entity("EfCoreMigrationandConfiguration.Models.Ogrenci", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"), 1L, 1);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoyAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("TelNo");

                    b.HasKey("No");

                    b.ToTable("Ogrenci");
                });

            modelBuilder.Entity("EfCoreMigrationandConfiguration.Models.Not", b =>
                {
                    b.HasOne("EfCoreMigrationandConfiguration.Models.Ogrenci", "Ogr")
                        .WithMany()
                        .HasForeignKey("OgrNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogr");
                });
#pragma warning restore 612, 618
        }
    }
}
